### ISSUE TITLE
D6.2.1 Report: Architectural Design Document (ADD)

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Project-Management#83]

**Comment by mrostren** [comment]
The architectural Design is available on github WP6/ release D6.2.1-ArchitecturalDesign-V1.0-M06
The branch D6.2.1-ArchitecturalDesign will be always available to update the architecture. 
Please make sure that the D6.2.1-ArchitecturalDesign branch is rebased on the master branch before !
